apiVersion: apps/v1
kind: Deployment
metadata:
  name: sailor-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      appName: sailor
      version: "1.0"
  template:
    metadata:
      labels:
        appName: sailor
        version: "1.0"
    spec:
      containers:
        - name: sailor
          image: techsriman/sailor:1.0
          ports:
            - name: tomcatport
              containerPort: 8080
              protocol: TCP
          resources:
            requests:
              memory: "500Mi"
              cpu: "500m"
            limits:
              memory: "1024Mi"
              cpu: "1000m"
          readinessProbe:
            httpGet:
              path: /sailor/health/readiness.htm
              port: 8080
            initialDelaySeconds: 5
            timeoutSeconds: 10
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /sailor/health/liveness.htm
              port: 8080
            initialDelaySeconds: 15
            timeoutSeconds: 10
            failureThreshold: 3